services:
  - type: web
    name: scanify-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "5000"
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
